[general]
working_directory = "/home/arek/"
live_config_reload = true


[env]
# set env variables here 

[window]
opacity = 0.8
blur = true
title = "SudoIntellectual"
padding = { x = 10, y = 5 }
dynamic_padding = true

[font]
size = 8
normal = { family = "UbuntuSansMono Nerd Font", style = "Regular"}
bold = { family = "UbuntuSansMono Nerd Font", style = "Bold"}
italic = { family = "UbuntuSansMono Nerd Font", style = "Italic"}
bold_italic = { family = "UbuntuSansMono Nerd Font", style = "Bold Italic" }

[colors]
[colors.primary]
foreground = "#0bd092"


[keyboard]
#bindings = [
#  {key = "Enter", mods = "Command", action = "ToggleSimpleFullScreen"},
 # {key = "Enter", mods = "Command|Shift", action = "ToggleFullscreen"},
  #{key = "+", mods="Command", action="IncreaseFontSize"},
 # {key = "-", mods="Command", action="DecreaseFontSize"}
#]
